config/routes.rb
class SubdomainConstraint
  def self.matches?(request)     
    request.subdomain.present? && request.subdomain != 'www'   
  end 
end

Rails.application.routes.draw do

  # Public site
  root to: 'home#index'
  get 'about_us' => 'home#about_us', as: 'about_us'
  get 'pricing' => 'home#pricing', as: 'pricing'
  get 'consumers' => 'home#consumers', as: 'consumers'
  get 'privacy_policy' => 'home#privacy_policy', as: 'privacy_policy'
  get 'terms_of_service' => 'home#terms_of_service', as: 'terms_of_service'
  resources :contacts, only: %i[new create update]
  get 'contacts/thank_you' => 'contacts#thank_you', as: :thank_you

  # Users Setup
  devise_for :users,
    :controllers => {
      registrations: 'users/registrations',
      sessions:      'users/sessions'
    }

  namespace :users do
    get '/dashboard', to: 'dashboard#index', as: 'dashboard', controller: 'users/dashboard'
    resources :charges
    resources :apps
    resources :devices
    resources :administrators
    resources :settings
    resources :reports
    scope 'mfa' do
      get '/authenticate/new', to: 'mfa_authentications#new', as: 'authenticate', controller: 'users/mfa_authentications'
    end
    scope 'mfa' do
      get '/register/new', to: 'mfa_registrations#new', as: 'register', controller: 'users/mfa_registrations'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord

  # Simple authentication token for mobile apps
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :confirmable and :omniauthable

  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable

  before_validation :check_subdomain
  after_create :create_tenant

  def check_subdomain
    self.subdomain = Faker::Internet.domain_word unless subdomain.present?
  end

  def create_tenant 
    Apartment::Tenant.create(subdomain) 
  end
  private


end

app/controllers/users/administrators_controller.rb
class Users::AdministratorsController < ApplicationController
  def index

  end
end

app/controllers/users/apps_controller.rb
class Users::AppsController < ApplicationController
  def index

  end
end

app/controllers/users/charges_controller.rb
class Users::ChargesController < ApplicationController
  layout :resolve_layout

  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Signal 0x Lock Protection',
      currency: 'usd'
    )

    redirect_to new_users_account_path
  rescue Stripe::CardError => e
    flash[:error] = e.message

    redirect_to new_users_charge_path
  end

  private

  def resolve_layout
    'user'
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController
  before_action :authenticate_user!
  def index

  end

end

app/controllers/users/devices_controller.rb
class Users::DevicesController < ApplicationController
  def index

  end
end

app/controllers/users/mfa_authentications_controller.rb
class Users::MfaAuthenitcationsController < ApplicationController

  def new
    # Fetch existing Registrations from your db
    key_handles = Registration.map(&:key_handle)
    return 'Need to register first' if key_handles.empty?

    # Generate SignRequests
    @app_id = u2f.app_id
    @sign_requests = u2f.authentication_requests(key_handles)
    @challenge = u2f.challenge

    # Store challenge. We need it for the verification step
    session[:challenge] = @challenge

    render 'authentications/new'
  end

  def create
    response = U2F::SignResponse.load_from_json(params[:response])

    registration = Registration.first(key_handle: response.key_handle)
    return 'Need to register first' unless registration

    begin
      u2f.authenticate!(session[:challenge], response,
                        Base64.decode64(registration.public_key),
                        registration.counter)
    rescue U2F::Error => e
      return "Unable to authenticate: <%= e.class.name %>"
    ensure
      session.delete(:challenge)
    end

    registration.update(counter: response.counter)

    'Authenticated!'
  end

end

app/controllers/users/mfa_registrations_controller.rb
class Users::MfaRegistrationsController < ApplicationController

  def new
    # Generate one for each version of U2F, currently only `U2F_V2`
    # @registration_requests = u2f.registration_requests
    #
    # # Store challenges. We need them for the verification step
    # session[:challenges] = @registration_requests.map(&:challenge)
    #
    # # Fetch existing Registrations from your db and generate SignRequests
    # key_handles = Registration.map(&:key_handle)
    # @sign_requests = u2f.authentication_requests(key_handles)
    #
    # @app_id = u2f.app_id
    #
    # render 'mfa/register'
  end

  def create
    # response = U2F::RegisterResponse.load_from_json(params[:response])
    #
    # reg = begin
    #   u2f.register!(session[:challenges], response)
    # rescue U2F::Error => e
    #   return "Unable to register: <%= e.class.name %>"
    # ensure
    #   session.delete(:challenges)
    # end
    #
    # # save a reference to your database
    # Registration.create!(certificate: reg.certificate,
    #                      key_handle:  reg.key_handle,
    #                      public_key:  reg.public_key,
    #                      counter:     reg.counter)
    #
    # 'Registered!'
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # before_action :authenticate_user!
  skip_before_action :verify_authenticity_token




  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    users_dashboard_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


end

app/controllers/users/reports_controller.rb
class Users::ReportsController < ApplicationController
  def index

  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :authenticate_user!


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_signin_path_for(resource)
    users_dashboard_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/settings_controller.rb
class Users::SettingsController < ApplicationController
  def index

  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/users/charges/_pricing.html.erb
<%= form_tag users_charges_path do %>
<article>
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>

  <section id="pricing-option3" class="background1 section-padding">
    <div class="container">
      <div class="row">
        <div class="section-title col-xs-12 text-center">
          <h2>
            Select a Payment Option
          </h2>
          <span class="section-divider mb15"></span>
          <p class="no-margin">Checkout our payment options.</p>
        </div>
        <!-- /.column -->
      </div>
      <!-- /.row -->

      <div class="row mt50">
        <!-- Item 1 -->
        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 bottomReveal">
          <ul class="plan plan1">
            <li class="plan-name plan-name-option3">Basic
              <h2 class="no-margin">$50</h2>
              / annual</li>
            <!-- <li><strong>400GB</strong> Bandwidth</li> <li><strong>10</strong> Email Address</li> <li><strong>Forum</strong> Support</li> <li><strong>NO Free</strong> Squirel</li> -->
            <li class="plan-action">
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:stripe_publishable_key] %>" data-description="Basic plan subscription" data-label="Sign Up" data-amount="5000" data-locale="auto"></script>

            </li>
          </ul>
        </div>
        <!-- /.column -->

        <!-- Item 2 -->
        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 mt30-xs topReveal">
          <ul class="plan plan2">
            <li class="plan-name plan-name-option3">Standard
              <h2 class="no-margin">$100</h2>
              / annual</li>
            <!-- <li><strong>400GB</strong> Bandwidth</li> <li><strong>10</strong> Email Address</li> <li><strong>Forum</strong> Support</li> <li><strong>NO Free</strong> Squirel</li> -->
            <li class="plan-action">
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:stripe_publishable_key] %>" data-description="Standard subscription" data-label="Sign Up" data-amount="10000" data-locale="auto"></script>

            </li>
          </ul>
        </div>
        <!-- /.column -->

        <!-- Item 3 -->
        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 mt30-sm mt30-xs bottomReveal">
          <ul class="plan plan3">
            <li class="plan-name plan-name-option3">Advanced
              <h2 class="no-margin">$200</h2>
              / annual</li>
            <!-- <li><strong>1024GB</strong> Bandwidth</li> <li><strong>Unlimited</strong> Email Address</li> <li><strong>Forum</strong> Support</li> <li><strong>Free</strong> Squirel</li> -->
            <li class="plan-action">
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:stripe_publishable_key] %>" data-description="Advanced subscription" data-label="Sign Up" data-amount="20000" data-locale="auto"></script>

            </li>
          </ul>
        </div>
        <!-- /.column -->

        <!-- Item 4 -->
        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 mt30-sm mt30-xs topReveal">
          <ul class="plan plan4">
            <li class="plan-name plan-name-option3">Mighty
              <h2 class="no-margin">$400</h2>
              / annual</li>
            <!-- <li><strong>1024GB</strong> Bandwidth</li> <li><strong>Unlimited</strong> Email Address</li> <li><strong>Forum</strong> Support</li> <li><strong>Free</strong> Squirel</li> -->
            <li class="plan-action">
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:stripe_publishable_key] %>" data-description="Mighty subscription" data-label="Sign Up" data-amount="40000" data-locale="auto"></script>

            </li>
          </ul>
        </div>
        <!-- /.column -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container -->
  </section>
  <!-- /.section -->
  <!-- End Section 3 -->

</article>

<% end %>

app/views/users/charges/new.html.erb
<div class="container">
  <%= render "pricing" %>
</div>