config/routes.rb
class SubdomainConstraint
  def self.matches?(request)     
    request.subdomain.present? && request.subdomain != 'www'   
  end 
end

Rails.application.routes.draw do

  # Public site
  root to: 'home#index'
  get 'about_us' => 'home#about_us', as: 'about_us'
  get 'pricing' => 'home#pricing', as: 'pricing'
  get 'consumers' => 'home#consumers', as: 'consumers'
  get 'privacy_policy' => 'home#privacy_policy', as: 'privacy_policy'
  get 'terms_of_service' => 'home#terms_of_service', as: 'terms_of_service'
  resources :contacts, only: %i[new create update]
  get 'contacts/thank_you' => 'contacts#thank_you', as: :thank_you

  # Users Setup
  devise_for :users,
    :controllers => {
      registrations: 'users/registrations',
      sessions:      'users/sessions'
    }

  namespace :users do
    get '/dashboard', to: 'dashboard#index', as: 'dashboard', controller: 'users/dashboard'
    resources :charges
    resources :apps
    resources :devices
    resources :administrators
    resources :settings
    resources :reports
    scope 'mfa' do
      get '/authenticate/new', to: 'mfa_authentications#new', as: 'authenticate', controller: 'users/mfa_authentications'
    end
    scope 'mfa' do
      get '/register/new', to: 'mfa_registrations#new', as: 'register', controller: 'users/mfa_registrations'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  after_create :send_lead_email

  private

  def send_lead_email
    ContactMailer.lead_email(self).deliver_later
  end
end

app/models/mfa_registrations.rb
class MfaRegistrations < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord

  # Simple authentication token for mobile apps
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :confirmable and :omniauthable

  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable

  before_validation :check_subdomain
  after_create :create_tenant

  def check_subdomain
    self.subdomain = Faker::Internet.domain_word unless subdomain.present?
  end

  def create_tenant 
    Apartment::Tenant.create(subdomain) 
  end
  private


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout :layout_by_resource
  before_action :get_correct_subdomain


  private

  #   # override the devise helper to store the current location so we can
  #   # redirect to it after loggin in or out. This override makes signing in
  #   # and signing up work automatically.

  def get_correct_subdomain
    if user_signed_in?
      redirect_to root_url(subdomain: current_user.subdomain) if request.subdomain != current_user.subdomain
    end
  end

  def layout_by_resource
    if user_signed_in?
      'user'
    else
      'application'
    end
  end




end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update destroy]

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  def thank_you
    # code
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to thank_you_path, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to thank_you_path, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:name, :phone, :email, :catgegory, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # code
  end

  def about_us
    # code
  end

  def contact
    # code
  end

  def consumers
    
  end

  def enterprises
    
  end

  def pricing
    # code
  end

  def privacy_policy
    # code
  end

  def terms_of_service
    # code
  end
end

app/controllers/users/apps_controller.rb
class Users::AppsController < ApplicationController
  def index

  end
end

app/controllers/users/charges_controller.rb
class Users::ChargesController < ApplicationController
  layout :resolve_layout

  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Signal 0x Lock Protection',
      currency: 'usd'
    )

    redirect_to new_users_account_path
  rescue Stripe::CardError => e
    flash[:error] = e.message

    redirect_to new_users_charge_path
  end

  private

  def resolve_layout
    'user'
  end
end

app/controllers/users/devices_controller.rb
class Users::DevicesController < ApplicationController
  def index

  end
end

app/controllers/users/reports_controller.rb
class Users::ReportsController < ApplicationController
  def index

  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :authenticate_user!


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_signin_path_for(resource)
    users_dashboard_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/settings_controller.rb
class Users::SettingsController < ApplicationController
  def index

  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def build_shutdown_url application
    signature = Base64.urlsafe_encode64(current_user.rsa_signature)

    "#{application.host}/shutdown/?token=#{application.access_tokens.first.token}&signature=#{signature}"
  end
end

app/helpers/authenticated_apps_helper.rb
module AuthenticatedAppsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/issue_shutdowns_helper.rb
module IssueShutdownsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/restore_accounts_helper.rb
module RestoreAccountsHelper
end

app/views/application/_footer.html.erb
<!-- ========== FOOTER ========== -->
<footer class="light-footer">
	<div class="container">
		<div class="row">
			<div class="col-md-2 col-sm-3 col-xs-6">
				<%= image_tag('deauthorized.png', class: "footer-logo") %>
			</div>

			<div class="col-md-2 col-sm-3 col-xs-6">
				<h6 class="mtn">HOME</h6>
				<ul>
					<li>
						<%= link_to "Home", root_path %>
					</li>
					<!-- <li> <%= link_to "About Us", about_us_path %> </li> <li> <%= link_to "Pricing", pricing_path %> </li> -->
					<li>
						<%= link_to "Privacy Policy", privacy_policy_path %>
					</li>
					<li>
						<%= link_to "Terms of Service", terms_of_service_path %>
					</li>
				</ul>
			</div>

			<div class="col-md-2 col-sm-3 col-xs-6">
				<h6 class="mtn">CONSUMERS</h6>
				<ul>
					<li>
						<%= link_to "Features", consumers_path %>
					</li>
					<li>
						<%= link_to "Login", new_user_session_path %>
					</li>
					<li>
						<%= link_to "Sign Up", new_user_registration_path %>
					</li>

				</ul>
			</div>

			<div class="col-md-4 col-sm-8 col-sm-offset-2 col-md-offset-0">
				<h6 class="mtn">SUBSCRIBE</h6>
				<div class="input-group">
					<input type="email" class="form-control inp-rounded" placeholder="Enter your email id">
					<span class="input-group-btn">
						<button class="btn se-btn btn-rounded" type="button">Subscribe!</button>
					</span>
					<!-- end input-group-btn -->
				</div>
				<!-- end input-group -->
				<p class="text-center text-muted">We don't spam!</p>
			</div>
		</div>
		<!-- end row -->

		<div class="row footer-bottom">
			<div class="col-md-6">
				<p>Copyright &copy; Deauthorized 2017. All Rights Reserved.</p>
			</div>

			<div class="col-md-6 text-right">
				<h6>
					<a href="https://facebook.com/deauthorized" target="_blank">FACEBOOK</a>
				</h6>
				<h6>
					<a href="https://twitter.com/deauthorized" target="_blank">TWITTER</a>
				</h6>
				<h6>
					<a href="https://medium.com/@deauthorized" target="_blank">MEDIUM</a>
				</h6>
			</div>
		</div>
		<!-- end footer-bottom -->
	</div>
	<!-- end container -->
</footer>

app/views/application/_header.html.erb
<!-- ========== NAVIGATION ========== -->
<nav class="navbar yamm navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- end navbar-toggle -->
      <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag('deauthorized-white.png', class: "light-logo") %>
      <%= image_tag('deauthorized.png', class: "dark-logo") %>
    <% end %>
    <!-- end navbar-brand -->
  </div>
  <!-- end navbar-header -->

  <div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav pull-right">
      <li class="active">
        <%= link_to "Home", root_path %>
      </li>
      <li><%= link_to "About", consumers_path %></li>
      <li><%= link_to "Login", new_user_session_path %></li>
      <li><%= link_to "Register", new_user_registration_path %></li>
      <li><%= link_to "Request a Demo", new_contact_path %></li>
      <li>
        <a href="https://medium.com/@deauthorized" target="_blank">Blog</a>
      </li>
      <!-- <li class="nav-btn-wrap"> <span class="nav-btn"><%= link_to "User Sign Up", new_user_session_path, class: "btn se-btn-black btn-rounded" %></span> </li> -->
    </ul>

  </div>
</div>
</nav>

app/views/application/_scripts.html.erb
<!-- Start of HubSpot Embed Code -->
<script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/3970341.js"></script>
<!-- End of HubSpot Embed Code -->

app/views/application/_sidebar.html.erb
<nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <%= link_to "Dashboard", users_dashboard_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Applications", users_apps_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Registered Users", users_apps_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "2FA Devices", users_devices_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Adminstrators", users_administrators_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Reports", users_reports_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Settings", users_settings_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Subscription", new_users_charge_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Account", edit_user_registration_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Logout", destroy_user_session_path, class: "nav-link", :method => :delete %>
    </li>
  </ul>

</nav>

app/views/application/_user_footer.html.erb
<footer class="footer-padding">
	<div class="container">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2 text-center"></div>
		</div>
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2 text-small text-center">
				<p class="no-margin">&copy; Deauthorized</p>
			</div>
			<!-- /.column -->
		</div>
		<!-- /.row -->
	</div>
	<!-- /.container -->
</footer>
<!-- /.footer -->

app/views/application/_user_header.html.erb
<!-- Begin Header -->

<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse nav-fix">
  <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Deauthorized</a>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <!-- <li class="nav-item active"> <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> </li> <li class="nav-item"> <a class="nav-link" href="#">Settings</a> </li> <li class="nav-item"> <a class="nav-link" href="#">Profile</a>
      </li> -->

      <!-- <li> <a class="nav-link" href="#">Help</a> </li> -->

    </ul>
    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>